version: '3.8'

services:
  backend-app:
    image: ${BACKEND_IMAGE}
    container_name: backend-container
    restart: unless-stopped
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ALLOWED_PATTERN=${CORS_ALLOWED_PATTERN}
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN}